### ISSUE TITLE
Unable to initialize policy entry: unknown protocol: vfs

### ISSUE THREAD

**Issue by JeremJR** [pro-grade/pro-grade#30]
Hello,

I would like to use pro-grade (1.1.1) to prevent some malicious executions from an ear application deployed inside JBoss-7.1.1.
I've used it in generator mode and it effectively creates entries like : 
grant codeBase "vfs:/content/myapp.ear/lib/my.jar" {
  permission java.io.FilePermission "/bin/bash", "execute";
};

But when I try to load this policy in standard mode it raises : 
"Unable to initialize policy entry: unknown protocol: vfs"

Thanks in advance for your help.

**Comment by kwart** [comment]
I think, it'll not work in AS 7.1.1. 

There were several problems with using security manager in AS 7.x (missing policy refresh after registering VFS protocol, permissions for server modules, ...). The error message about the unknown protocol itself is not a problem - it's expected behavior (Java doesn't know about VFS protocol - it has to be registered and then the policy file has to be re-read).

The problems were fixed in supported version - JBoss EAP  (version 6.2.3 if I recall correctly). The JBoss EAP 6.x is based on JBoss AS 7.x - the version numbers can be a little bit missleading.

You can try [JBoss EAP 6.x for developers](http://www.jboss.org/products/eap/overview/) (current version is 6.4.0)

There is another problem with EAP 6.4.x - it doesn't support custom security managers - so the policy file generator will not work for you. The simplest would be if you can find JBoss EAP 6.3.0 - we even have [wiki tutorial](https://sourceforge.net/p/pro-grade/wiki/PolicyGeneratorWithJBossEAP6.3/) how to configure it with pro-grade.

We have a plan to update the generator and documentation to cover also EAP 6.4.x, but it's still only a plan...

**Comment by JeremJR** [comment]
Ok thanks for the explanation. There is no way to register VFS protocol in AS 7.1.1 before reading the policy?

**Comment by kwart** [comment]
I don't know any... Maybe to make your own launcher, which registers the URL handler and then gives control to JBoss Modules. Or try to use newer version of [JBoss Modules](https://github.com/jboss-modules/jboss-modules)

The EAP 6.3 used JBoss Modules in [version 1.3.3.Final](https://github.com/jboss-modules/jboss-modules/tree/1.3.3.Final).

**Comment by JeremJR** [comment]
Ok thank you.
